meta_product_name: "Taskete"
meta_title: "Taskete - Help organising tasks!"
meta_description: "Taskete.co is the Best Tool to get Your Team Inline with Your Vision. Try Taskete now for free. Boost your Productivity and get Tasks Done Faster."
meta_image: "Taskete_logo.png" # should exist in `app/assets/images/`